export GIT_BYPASS = 0

# Define Firmware Version Number
export PRJ_VERSION = 0x00000010

# Define the Hardware Type in the axi-pcie-core
export PCIE_HW_TYPE = XilinxKcu1500

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

# Define the number of MIG cores
export NUM_MIG_CORES = 0

# Define the DDR speed (in units of Mbps)
export DDR_SPEED = 2400

# Select either GEN1 or GEN2 or GEN3 PCIe
export PCIE_GEN_NUM = GEN2

# BYPASS Partial Reconfiguration
export BYPASS_RECONFIG = 1

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
