export INCLUDE_PGP3_10G = 0
#export REMOVE_UNUSED_CODE = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x10000000

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e


export OVERRIDE_SUBMODULE_LOCKS = 0

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
