# Define Firmware Version Number
export PRJ_VERSION = 0x00000011

export TIMING_EXT_PKG = 1

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

#simulation package export
export TIMING_EXT_PKG = 1

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
